# Generated by Django 3.1.12 on 2021-06-24 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0002_auto_20210624_0634'),
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_pay', models.BooleanField(default=False)),
                ('chair_number', models.SmallIntegerField()),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passenger.passengermodel')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.travelmodel')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
