# Generated by Django 3.1.12 on 2021-06-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20210624_0857'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_travel', to='trip.travelmodel'),
        ),
    ]
