# Generated by Django 3.1.12 on 2021-06-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20210624_1812'),
        ('ticket', '0002_auto_20210624_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_travel_set', related_query_name='ticket_travel_set', to='trip.travelmodel'),
        ),
    ]
