# Generated by Django 3.1.12 on 2021-06-23 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_driver', '0001_initial'),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival', to='trip.destinationmodel')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure', to='trip.destinationmodel')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='TravelModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('price', models.PositiveSmallIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus.busmodel')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus_driver.busdrivermodel')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.tripmodel')),
            ],
            options={
                'db_table': 'travel',
            },
        ),
    ]
