# Generated by Django 3.1.12 on 2021-06-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20210624_0634'),
        ('trip', '0002_auto_20210624_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmodel',
            name='assigned_buses',
            field=models.ManyToManyField(to='bus.BusModel'),
        ),
    ]
