# Generated by Django 3.1.12 on 2021-06-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_tripmodel_assigned_buses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
