# Generated by Django 3.1.12 on 2021-06-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20210624_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelmodel',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_travel', to='trip.tripmodel'),
        ),
    ]
