# Generated by Django 3.1.12 on 2021-06-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20210624_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelmodel',
            name='driver',
        ),
    ]
