# Generated by Django 3.1.12 on 2021-06-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_travelmodel_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmodel',
            name='tickets_sold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='travelmodel',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_trip_set', related_query_name='travel_trip_set', to='trip.tripmodel'),
        ),
    ]
