# Generated by Django 3.1.12 on 2021-06-23 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate', models.BooleanField()),
                ('is_available', models.BooleanField()),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_driver.busdrivermodel')),
            ],
            options={
                'db_table': 'bus',
            },
        ),
    ]
