# Generated by Django 3.1.12 on 2021-06-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='busmodel',
            name='plate',
            field=models.CharField(max_length=15),
        ),
    ]
